# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2DEbqdRBHlPcYosQwyONMAags2hP9QJ
"""

import json
from datetime import datetime

def load_data(file_name):
    try:
        with open(file_name, 'r') as file:
            return json.load(file)
    except FileNotFoundError:
        return {'patients': [], 'appointments': []}

def save_data(file_name, data):
    with open(file_name, 'w') as file:
        json.dump(data, file)

def add_patient(patients, name, phone):
    for patient in patients:
        if patient['phone'] == phone:
            print("Paciente já cadastrado!")
            return patients

    patients.append({'name': name, 'phone': phone})
    print("Paciente cadastrado com sucesso.")
    return patients

def list_patients(patients):
    for i, patient in enumerate(patients, start=1):
        print(f"{i}. {patient['name']} ({patient['phone']})")
    return patients

def add_appointment(appointments, patients, patient_index, date, time, specialty):
    patient = patients[patient_index - 1]
    appointment = {
        'date': date,
        'time': time,
        'specialty': specialty,
        'patient': patient
    }
    appointments.append(appointment)
    print("Consulta marcada com sucesso.")
    return appointments

def list_appointments(appointments):
    for i, appointment in enumerate(appointments, start=1):
        patient_name = appointment['patient']['name']
        print(f"{i}. {patient_name} - {appointment['date']} {appointment['time']} - {appointment['specialty']}")
    return appointments

def cancel_appointment(appointments, appointment_index):
    del appointments[appointment_index - 1]
    print("Consulta cancelada com sucesso.")

def main():
    data = load_data('clinic_data.json')
    patients = data['patients']
    appointments = data['appointments']

    while True:
        print("\n1. Cadastrar um paciente")
        print("2. Marcações de consultas")
        print("3. Cancelamento de consultas")
        print("4. Sair")

        option = int(input("Escolha uma opção: "))

        if option == 1:
            name = input("Digite o nome do paciente: ")
            phone = input("Digite o telefone do paciente: ")
            patients = add_patient(patients, name, phone)
        elif option == 2:
            patients = list_patients(patients)
            patient_index = int(input("Escolha o número do paciente: ")) - 1
            date = input("Digite a data da consulta (dd/mm/aaaa): ")
            time = input("Digite a hora da consulta (hh:mm): ")
            specialty = input("Digite a especialidade da consulta: ")
        elif option == 3:
            appointments = list_appointments(appointments)
            appointment_index = int(input("Escolha o número da consulta: ")) - 1
            cancel_appointment(appointments, appointment_index)
        elif option == 4:
            save_data('clinic_data.json', data)
            print("Obrigado por utilizar nosso serviço!")
            break
        else:
            print("Opção inválida. Tente novamente.")

if __name__ == "__main__":
    main()